/*
 * File: app/view/inventory/List.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('coloMS.view.inventory.List', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.inventoryList',

    requires: [
        'Ext.grid.plugin.RowEditing',
        'Ext.toolbar.Paging'
    ],

    height: 250,
    width: 400,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    text: 'Name',
                    flex: 0.2,
                    editor: {
                        xtype: 'textfield',
                        allowBlank: false,
                        maxLength: 255
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'description',
                    text: 'Descripton',
                    flex: 0.5,
                    editor: {
                        xtype: 'textfield',
                        maxLength: 255
                    }
                }
            ],
            plugins: [
                Ext.create('Ext.grid.plugin.RowEditing', {

                })
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'add',
                            iconCls: 'silk-add',
                            text: 'Add'
                        }
                    ]
                },
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    defaultButtonUI: 'default',
                    displayInfo: true,
                    store: 'inventory.Vendors'
                }
            ]
        });

        me.callParent(arguments);
    }

});