/*
 * File: app/view/layout/Menu.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('coloMS.view.layout.Menu', {
    extend: 'Ext.menu.Menu',
    alias: 'widget.layoutMenu',

    floating: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'menuitem',
                    itemId: 'options',
                    iconCls: 'silk-group',
                    text: 'Options'
                },
                {
                    xtype: 'menuseparator'
                },
                {
                    xtype: 'menuitem',
                    itemId: 'staff',
                    text: 'Sales Staff'
                },
                {
                    xtype: 'menuseparator'
                },
                {
                    xtype: 'menuitem',
                    itemId: 'inventory',
                    iconCls: 'silk-server-link',
                    text: 'Inventory',
                    menu: {
                        xtype: 'menu',
                        items: [
                            {
                                xtype: 'menuitem',
                                itemId: 'inventory-vendors',
                                text: 'Vendors'
                            }
                        ]
                    }
                }
            ]
        });

        me.callParent(arguments);
    }

});