/*
 * File: app/view/layout/South.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('coloMS.view.layout.South', {
    extend: 'Ext.container.Container',
    alias: 'widget.layoutSouth',

    style: 'background-color:cornflowerblue',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'label',
                    name: 'copiright',
                    style: 'color:white;font-size:12px',
                    text: '(с) ColoBridge Gmbh 2013'
                }
            ]
        });

        me.callParent(arguments);
    }

});